name: PR Code Quality Check & Telegram Notification

# 스크립트 실행 시기
on:
  pull_request:
    # pr 생성, pr 업데이트(코드 변경), 리뷰어 지정 시 발생
    types: [opened, synchronize, review_requested]
    # develop이나 main에 pr을 하려고 할때
    branches: [ "main", "develop" ]

permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Telegram으로 PR 알림 보내기
        # PR을 처음 생성하거나 리뷰어를 지정했을 때만 텔레그램 알림 전송
        if: github.event.action == 'opened' || github.event.action == 'review_requested'
        uses: F2had/pr-telegram-action@v1.0.0
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: 코드 가져오기
        uses: actions/checkout@v3
        with:
          # 깃 히스토리 가져오기
          fetch-depth: 0

      - name: JDK 21 세팅
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven 실행 권한 부여
        run: chmod +x ./mvnw

      # develop 브랜치 소나큐브 적용
      - name: 코드 빌드 및 소나큐브 분석 (Develop)
        if: github.base_ref == 'develop'
        run: >
          ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Djacoco.haltOnFailure=false
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=4iren-eureka

      # main 브랜치 소나큐브 적용
      - name: 코드 빌드 및 소나큐브 분석 (Main)
        if: github.base_ref == 'main'
        run: >
          ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Djacoco.haltOnFailure=true
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=4iren-eureka
          -Dsonar.qualitygate.wait=true

      # ==========================================
      # pr 화면에 소나큐브 리포트 링크 댓글 달기
      # ==========================================
      - name: PR에 소나큐브 링크 댓글 작성
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() # 성공하든 실패하든 무조건 댓글 달기
        with:
          header: sonarqube-report
          recreate: true
          message: |
            ### 🔍 SonarQube 분석 완료!
            - 타깃 브랜치: `${{ github.base_ref }}`
            - 분석 결과: `${{ job.status }}`

            📊 **소나큐브 상세 리포트 확인하러 가기**
            - 🏢 [**내부망에서 접속 시 클릭**](http://10.116.64.14:9000/dashboard?id=4iren-eureka&codeScope=overall)
            - 🏠 [**외부망에서 접속 시 클릭**](<${{ secrets.SONAR_HOST_URL }}dashboard?id=4iren-eureka&codeScope=overall>)